### ISSUE TITLE
BadDsn: Unsupported scheme ''

### ISSUE THREAD

**Issue by nborrmann** [getsentry/sentry_airflow#15]
I have configured `sentry-airflow` as described in the instructions. But during startup I get the following exception:

```
[2019-08-27 14:38:16,807] {plugins_manager.py:143} ERROR - Unsupported scheme ''
Traceback (most recent call last):
  File "airflow/lib/python3.6/site-packages/airflow/plugins_manager.py", line 137, in <module>
    m = imp.load_source(namespace, filepath)
  File "/usr/lib/python3.6/imp.py", line 172, in load_source
    module = _load(spec)
  File "<frozen importlib._bootstrap>", line 684, in _load
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "airflow/plugins/sentry-airflow/sentry_plugin/__init__.py", line 2, in <module>
    from .hooks.sentry_hook import SentryHook
  File "airflow/plugins/sentry-airflow/sentry_plugin/hooks/sentry_hook.py", line 131, in <module>
    SentryHook()
  File "airflow/plugins/sentry-airflow/sentry_plugin/hooks/sentry_hook.py", line 120, in __init__
    init(dsn=dsn, integrations=integrations)
  File "airflow/lib/python3.6/site-packages/sentry_sdk/hub.py", line 84, in _init
    client = Client(*args, **kwargs)  # type: ignore
  File "airflow/lib/python3.6/site-packages/sentry_sdk/client.py", line 80, in __init__
    self._init_impl()
  File "airflow/lib/python3.6/site-packages/sentry_sdk/client.py", line 96, in _init_impl
    self.transport = make_transport(self.options)
  File "airflow/lib/python3.6/site-packages/sentry_sdk/transport.py", line 261, in make_transport
    return transport_cls(options)
  File "airflow/lib/python3.6/site-packages/sentry_sdk/transport.py", line 92, in __init__
    Transport.__init__(self, options)
  File "airflow/lib/python3.6/site-packages/sentry_sdk/transport.py", line 48, in __init__
    self.parsed_dsn = Dsn(options["dsn"])
  File "airflow/lib/python3.6/site-packages/sentry_sdk/utils.py", line 91, in __init__
    raise BadDsn("Unsupported scheme %r" % parts.scheme)
```

The error seems to be in line 117 of `sentry_hook.py`:
```
            dsn = conn_id.host
```
The host part of the connection is just `sentry.io`, which is obviously not a valid Dsn and causes the error above.

I have fixed the error by replacing this line with 
```
            dsn = f"{conn_id.conn_type}://{conn_id.login}@{conn_id.host}/{conn_id.schema}"
```

**Comment by nborrmann** [comment]
This approach is incompatible with setting the Dsn via an environment variable (as described in the Readme). Sentry automatically parses that, and the host becomes just `sentry.io`.

I actually think the way I fixed it is the right way to do it. The `DbApiHook` does a very similar thing:
```python
    def get_uri(self):
        conn = self.get_connection(getattr(self, self.conn_name_attr))
        login = ''
        if conn.login:
            login = '{conn.login}:{conn.password}@'.format(conn=conn)
        host = conn.host
        if conn.port is not None:
            host += ':{port}'.format(port=conn.port)
        return '{conn.conn_type}://{login}{host}/{conn.schema}'.format(
            conn=conn, login=login, host=host)
```
The naming in airflow is just a bit odd (the uri-path being called `conn.schema`, and the uri-schema being called `conn.conn_type`.
